# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: model_registry.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'model_registry.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14model_registry.proto\x12\x10orchestration.v1\"q\n\x14RegisterModelRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\x0f\n\x07\x62\x61\x63kend\x18\x03 \x01(\t\x12\x14\n\x0c\x61rtifact_uri\x18\x04 \x01(\t\x12\x13\n\x0b\x63onfig_json\x18\x05 \x01(\t\")\n\x15RegisterModelResponse\x12\x10\n\x08model_id\x18\x01 \x01(\t\"0\n\x0fGetModelRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\"\x7f\n\x10GetModelResponse\x12\x10\n\x08model_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\t\x12\x0f\n\x07\x62\x61\x63kend\x18\x04 \x01(\t\x12\x14\n\x0c\x61rtifact_uri\x18\x05 \x01(\t\x12\x13\n\x0b\x63onfig_json\x18\x06 \x01(\t\"!\n\x11ListModelsRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"H\n\x12ListModelsResponse\x12\x32\n\x06models\x18\x01 \x03(\x0b\x32\".orchestration.v1.GetModelResponse\"&\n\x12\x44\x65leteModelRequest\x12\x10\n\x08model_id\x18\x01 \x01(\t\"\x07\n\x05\x45mpty2\xeb\x02\n\rModelRegistry\x12`\n\rRegisterModel\x12&.orchestration.v1.RegisterModelRequest\x1a\'.orchestration.v1.RegisterModelResponse\x12Q\n\x08GetModel\x12!.orchestration.v1.GetModelRequest\x1a\".orchestration.v1.GetModelResponse\x12W\n\nListModels\x12#.orchestration.v1.ListModelsRequest\x1a$.orchestration.v1.ListModelsResponse\x12L\n\x0b\x44\x65leteModel\x12$.orchestration.v1.DeleteModelRequest\x1a\x17.orchestration.v1.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'model_registry_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REGISTERMODELREQUEST']._serialized_start=42
  _globals['_REGISTERMODELREQUEST']._serialized_end=155
  _globals['_REGISTERMODELRESPONSE']._serialized_start=157
  _globals['_REGISTERMODELRESPONSE']._serialized_end=198
  _globals['_GETMODELREQUEST']._serialized_start=200
  _globals['_GETMODELREQUEST']._serialized_end=248
  _globals['_GETMODELRESPONSE']._serialized_start=250
  _globals['_GETMODELRESPONSE']._serialized_end=377
  _globals['_LISTMODELSREQUEST']._serialized_start=379
  _globals['_LISTMODELSREQUEST']._serialized_end=412
  _globals['_LISTMODELSRESPONSE']._serialized_start=414
  _globals['_LISTMODELSRESPONSE']._serialized_end=486
  _globals['_DELETEMODELREQUEST']._serialized_start=488
  _globals['_DELETEMODELREQUEST']._serialized_end=526
  _globals['_EMPTY']._serialized_start=528
  _globals['_EMPTY']._serialized_end=535
  _globals['_MODELREGISTRY']._serialized_start=538
  _globals['_MODELREGISTRY']._serialized_end=901
# @@protoc_insertion_point(module_scope)
